root: true

env:
  browser: false
  commonjs: true
  es6: true
  jest: node
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'plugin:security/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  eol-last: error
  eqeqeq: [error, allow-null]
  linebreak-style:
    - error
    - unix
  no-trailing-spaces: error
  no-unused-vars: [error, { vars: all, args: none, ignoreRestSiblings: true }]
