version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  test:
    executor:
      name: node/default
      tag: "13.2"
    steps:
      - checkout
      - run: ci
      - run: npm run ci
workflows:
    "Test":
      jobs:
        - test
